name: main
on:
  - pull_request
  - push
jobs:
  main:
    name: ${{matrix.node}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: ${{matrix.node}}
      - run: npm install
      - name: Cherry pick https://github.com/remarkjs/remark-lint/pull/283
        run: |
          curl https://patch-diff.githubusercontent.com/raw/remarkjs/remark-lint/pull/283.patch |
          git apply -p 3 --ignore-space-change --directory node_modules/unified-lint-rule
      - run: npm test
      - uses: codecov/codecov-action@v3
    strategy:
      matrix:
        node:
          - lts/fermium
          - node
